config/routes.rb
Rails.application.routes.draw do
  get 'products/create'

  get 'products/new'

  get 'products/edit'

  get 'products/update'

  get 'products/destroy'

  get 'products/show'

  get 'products/index'

  get 'tags/create'

  get 'tags/edit'

  get 'tags/new'

  get 'tags/update'

  get 'tags/destroy'

  get 'tags/show'

  get 'tags/index'

  get 'home/index'

  get 'home/contact'

  get 'categories/create'

  get 'categories/new'

  get 'categories/edit'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'contact' => 'home#contact'

  get 'home' => 'home#index'

  root 'home#index'

  resources :products
  resources :tags
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :tag
	has_one :category
	belongs_to :category
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @products = Product.all
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end

  def new
    @products = Product.all
    @content = "New Category"
    @category = Category.new
  end

  def edit
    @products = Product.all
    @content = "Edit Category"
    @category = Category.find(params[:id])
    redirect_to categories_path
  end

  def update
    @products = Product.all
    @category = Category.find(params[:id])
    @category = Category.update_attributes(category_params)
    redirect_to categories_path
  end

  def destroy
    @products = Product.all
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def index
    @products = Product.all
    @content = "Categories"
    @categories = Category.all
  end

  def show
    @content = "Products to Categories"
    @categories = Category.all
    @category = Category.find(params[:id])
    @title = @category.name
    @productCategory = @category.products
    @products = Product.all
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@page_title = "Home"
  	@content = "Welcome a board!"
  	@categories = Category.all
  	@products = Product.all
  	@tags = Tag.all
  end

  def contact
    @products = Product.all
  	@page_title = "Contact"
  	render 'contact'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to products_path
  end

  def edit
    @products = Product.all
    @content = "Edit Work"
    @product = Product.find(params[:id])
  end

  def new
    @content = "New Work"
    @product = Product.new
    @category = Category.all
    @tag = Tag.all
    @products = Product.all
  end

  def update
    @products = Product.all
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end

  def show
    @products = Product.all
    @product = Product.find(params[:id])
    @content = @product.name
    @categories = Category.all
  end

  def index
    @content = "New work"
    @products = Product.all
    @categories = Category.all
    @tags = Tag.all
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :image, :price, :tag_id, :category_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @products = Product.all
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to tags_path
  end

  def edit
    @products = Product.all
    @content = "Edit Tag"
  end

  def new
    @products = Product.all
    @content = "New Tag"
    @tag = Tag.new
  end

  def update
    @products = Product.all
    @tag = Tag.find(params[:id])
    @tag = Tag.update_attributes(tag_params)
  end

  def destroy
    @products = Product.all
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  def show
    @content="Tags for Products"
    @tags = Tag.all
    @products = Product.all
    @tag = Tag.find(params[:id])
    @tagEach = @tag.products
  end

  def index
    @products = Product.all
    @content="Tags"
    @content = "Tags"
    @tags = Tag.all
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @category do |c| %>
		
		<%= c.label :name %><br />
		<%= c.text_field :name, class:'form-control'%>

		<%= c.submit 'UPDATE', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/categories/index.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
	<div>
	<ul>
		<% @categories.each do |c| %>
		
			<li><%= c.name %></li> <%= link_to 'Delete', c, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br />
		<% end %>

	</ul>
	</div>
		<%= link_to 'New', new_category_path, class: 'btn btn-primary' %>

</div>

app/views/categories/new.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @category do |c| %>
		
		<%= c.label :name %><br />
		<%= c.text_field :name, class:'form-control', :autofocus => true%>

		<%= c.submit 'OK', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/categories/show.html.erb
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	<% @productCategory.each do |product| %>
		<%= link_to product.name, product %><br />
		<%= image_tag(product.image) %><br />
		<%= product.description%><br />
		<%= product.price %><br />
		<hr>
	<% end %>

	<%= link_to 'Back', products_path, class:'btn btn-primary' %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
	<div class="row">
	<% @products.each do |product| %>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="product-showcase">
				<a href="<%= product_path(product) %>">
					<div id="link-box">
						<div class="image-box">
							<%= image_tag(product.image) %>
						</div>
						<div>
							<h4><%= product.name %></h4>
							<p><small><%= product.description %></small></p>
							<h3 id="price"><%= product.price %></h3>
						</div>
					</div>
				</a>
				<div class="price-box">
					<button class="btn btn-primary"><%=link_to 'Buy', product_path(product) %></button>
				</div>
			</div>
			
		</div>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uclu</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  

  </head>

  <body>
      <%= render 'partials/navigation' %>

    <div class="container">
      <div class="row">
      <%= render 'partials/sidebar' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <%= link_to 'Shoppar', root_path, class:'navbar-brand'%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= @page_title='Home' ? 'active' : '' %>"><%= link_to 'Home', root_path, class:"nav-link" %><span class="sr-only">(current)</span></li>
              <li class="nav-item <%= @page_title = 'Contact' ? 'active' : '' %>"><%= link_to 'Contact', contact_path, class:"nav-link" %></li>
            </ul>
            <ul class="navbar-nav navbar-right">
              <form class="form-inline my-2 my-md-0">
                <input class="form-control" type="text" placeholder="Search" aria-label="Search">
              </form>
            </ul>

            <ul class="navbar-nav navbar-right">
             <div class="dropdown show">
              <a class="nav-item nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add New</a>
              <div class="dropdown-menu" aria-labelledby="dropdown07">
                <%= link_to 'Product', new_product_path, class:'dropdown-item'%>
                <%= link_to 'Category', new_category_path, class:'dropdown-item' %>
                <%= link_to 'Tag', new_tag_path, class:'dropdown-item' %>
              </div>
            </div>
          </ul>

          <ul class="navbar-nav navbar-right">
             <div class="dropdown show">
              <a class="nav-item nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Show All</a>
              <div class="dropdown-menu" aria-labelledby="dropdown07">
                <%= link_to 'Show Products', products_path, class:'dropdown-item'%>
                <%= link_to 'Show Categories', categories_path, class:'dropdown-item' %>
                <%= link_to 'Show Tags', tags_path, class:'dropdown-item' %>
              </div>
            </div>
          </ul>



          </div>
      </div>
</nav>

    <div class="container">
        <header>
          <div class="gray-bg">
            <h2><%= @content %></h2>
          </div>
        </header>
    </div>

app/views/partials/_sidebar.html.erb
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	<div id="sidebar">
		<ul>
			<% @products.each do |p| %>
			<li><%=link_to p.category.name,category_path(:id => p.category.id) %></li>
			<% end %>
		</ul>
	</div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @product do |p| %>
		
		<%= p.label :name %><br />
		<%= p.text_field :name, class:'form-control'%>

		<%= p.label :description %><br />
		<%= p.text_field :description, class:'form-control' %>

		<%= p.label :image %><br />
		<%= p.text_field :image, class:'form-control' %>

		<%= p.label :price %><br />
		<%= p.text_field :price, class:'form-control' %>

		<%= p.label :tag %><br />
		<%= p.collection_select :tag_id, Tag.all, :id, :name, prompt: true %><br />

		<div class="form-group">
		<%= p.label :category, for:'exampleFormControlSelect1' %><br />
		<%= p.collection_select :category_id, Category.all, :id, :name, prompt: true, class:'form-control', id:'exampleFormControlSelect1' %><br />
		</div>

		<%= p.submit 'UPDATE', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/products/index.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">image</th>
      <th scope="col">Price</th>
      <th scope="col">Tags</th>
      <th scope="col">Category</th>
    </tr>
  </thead>
  <tbody>

  <% @products.each do |p| %>
  <tr>
      <th scope="row"><%=p.id%></th>
      <td><%=p.name%></td>
      <td><%=p.description%></td>
      <td><%=p.image %></td>
      <td><%=p.price %></td>
      <td><%= link_to p.tag.name, tag_path(:id => p.tag.id) %></td>
      <td><%= link_to p.category.name, category_path(:id => p.category.id) %></td>
      <td><%= link_to 'Edit', edit_product_path(p), class:'btn btn-warning'%></td>
    </tr>
    <% end %>

  </tbody>
</table>
<%= link_to "Ok", root_path, class:'btn btn-primary' %>
<%= link_to "New", new_product_path, class:'btn btn-secondary' %>

</div>

app/views/products/new.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @product do |p| %>
		
		<%= p.label :name %><br />
		<%= p.text_field :name, class:'form-control', :autofocus => true %>

		<%= p.label :description %><br />
		<%= p.text_field :description, class:'form-control' %>

		<%= p.label :image %><br />
		<%= p.text_field :image, class:'form-control' %>

		<%= p.label :price %><br />
		<%= p.text_field :price, class:'form-control' %>

		<%= p.label :tag %><br />
		<%= p.select :tag_id, Tag.all.collect {|x| [x.name, x.id]}, {:prompt => "Please Select"}, { :multiple => true } %><br />

		<div class="form-group">
		<%= p.label :category, for:'exampleFormControlSelect1' %><br />
		<%= p.collection_select :category_id, Category.all, :id, :name, prompt: true, class:'form-control', id:'exampleFormControlSelect1' %><br />
		</div>

		<%= p.submit 'OK', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/products/show.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<%= image_tag @product.image %>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<h2><%= @product.name %></h2>
			<p><%= @product.description %></p>
			<h4><%= @product.price %></h4>
			<button class="btn btn-success"><%= link_to 'OK', root_path %></button>
		</div>
	</div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @tag do |t| %>
		
		<%= t.label :name %><br />
		<%= t.text_field :name, class:'form-control'%>

		<%= t.submit 'UPDATE', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/tags/index.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
	<div>
	<ul>
		<% @tags.each do |t| %>
		
			<li><%= t.name %></li> <%= link_to 'Delete', t, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br />
		<% end %>

	</ul>
	</div>
		<%= link_to 'New', new_tag_path, class: 'btn btn-primary' %>

</div>

app/views/tags/new.html.erb
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

	<%= form_for @tag do |t| %>
		
		<%= t.label :name %><br />
		<%= t.text_field :name, class:'form-control', :autofocus => true%>

		<%= t.submit 'OK', class: 'btn btn-primary' %>

	<% end %>

</div>

app/views/tags/show.html.erb
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	<% @tagEach.each do |tag| %>
		<h3><%= link_to tag.name, tag %></h3><br />
		<%= image_tag(tag.image) %><br />
		<%= tag.description%><br />
		<%= tag.price %><br />
		<hr>

	<% end %>

	<%= link_to 'Back', products_path, class:'btn btn-primary' %>
</div>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>